2020-09-27 15:57:24,440 ERROR: Exception on /user/Dima [GET] [in c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Floppy\Desktop\university\site\app\routes.py", line 106, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Floppy\Desktop\university\site\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Floppy\Desktop\university\site\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Floppy\Desktop\university\site\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Floppy\Desktop\university\site\app\templates\user.html", line 19, in block "app_content"
    {{ form.hidden_tag() }}
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-09-27 16:01:42,940 INFO: Microblog startup [in C:\Users\Floppy\Desktop\university\site\app\__init__.py:57]
2020-09-27 16:01:47,530 ERROR: Exception on /user/Dima [GET] [in c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Floppy\Desktop\university\site\app\routes.py", line 106, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-09-27 16:02:29,687 INFO: Microblog startup [in C:\Users\Floppy\Desktop\university\site\app\__init__.py:57]
2020-09-27 16:23:23,004 INFO: Microblog startup [in C:\Users\Floppy\Desktop\university\site\app\__init__.py:57]
2020-09-27 16:23:26,279 ERROR: Exception on /index [GET] [in c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Floppy\Desktop\university\site\app\routes.py", line 38, in index
    return render_template('index.html', title='Home', form=form,
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Floppy\Desktop\university\site\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Floppy\Desktop\university\site\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Floppy\Desktop\university\site\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Floppy\Desktop\university\site\app\templates\index.html", line 5, in block "app_content"
    <h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\ext.py", line 156, in gettext
    return rv % variables
  File "c:\users\floppy\appdata\local\programs\python\python38-32\lib\site-packages\markupsafe\__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
ValueError: unsupported format character '!' (0x21) at index 18
